[package]
name = "robomesh-python"
version = "0.1.1"
edition = "2021"

[lib]
name = "robomesh"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
robomesh = { path = ".." }
serde_json = "1.0"
